name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{env.node-version}}
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build doclink
