name: CI
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{env.node-version}}
          cache: yarn

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: npx nx build doclink
