name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_ADMIN_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
    paths:
      - 'apps/admin/**'
      - 'libs/admin/**'
      - '!docs/**'
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Install Nx CLI
        run: npm install --global @nrwl/cli nx
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
